# CodeRabbit Configuration File
# https://docs.coderabbit.ai/guides/configure-coderabbit
language: "pt-BR"
reviews:
  profile: "standard"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
