"""CLI command generator aligned to the taxonomy + architecture profile.

Turns a taxonomy + asset spec into the shell commands an operator (or a
CI/CD pipeline) needs to actually create the asset on the target cloud.
Every command:

* Honours the cloud-specific casing already enforced by :class:`DDLGenerator`.
* Honours the architectural prefix family (``dim_``, ``stg_``, ``hub_``).
* Honours ``lake_standards.zones`` for bucket / dataset / external location
  creation (so a ``raw`` zone bucket lands under the right prefix).
* Quotes shell arguments via :func:`shlex.quote` so taxonomy values cannot
  inject extra arguments (e.g. via a comment containing ``$(rm -rf /)``).

The generator never *executes* anything — it only emits the commands the
user (or CI) will run. That keeps it safe to embed in copilot UIs.
"""
from __future__ import annotations

import shlex
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence

from ...taxonomy.context import ArchitectureProfile
from ...taxonomy.models import TaxonomyDocument
from .ddl import DDLGenerationOptions, DDLGenerator, _cased


@dataclass
class CLICommand:
    tool: str                       # "bq" | "snowsql" | "gsutil" | "aws" | "dbt" | "terraform"
    description: str
    command: str
    requires_auth: bool = True
    cloud: Optional[str] = None

    def to_dict(self) -> Dict[str, object]:
        return {
            "tool": self.tool, "cloud": self.cloud,
            "description": self.description, "command": self.command,
            "requires_auth": self.requires_auth,
        }


@dataclass
class CLIPlan:
    """A bundle of commands that, executed in order, materializes an asset."""
    title: str
    commands: List[CLICommand] = field(default_factory=list)
    ddl: Optional[str] = None
    notes: List[str] = field(default_factory=list)

    def to_shell_script(self) -> str:
        """Render as a runnable bash script (with ``set -euo pipefail``)."""
        header = "\n".join([
            "#!/usr/bin/env bash",
            "# Generated by DataEngineeringAgent — review before executing.",
            f"# Asset: {self.title}",
            "set -euo pipefail",
            "",
        ])
        if self.ddl:
            header += "# --- DDL ---\n" + "\n".join("# " + l for l in self.ddl.splitlines()) + "\n\n"
        body = []
        for c in self.commands:
            body.append(f"# {c.description}")
            body.append(c.command)
            body.append("")
        notes = "\n".join(f"# NOTE: {n}" for n in self.notes)
        return header + "\n".join(body) + ("\n" + notes if notes else "")


class CLICommandGenerator:
    """Render cloud-specific commands aligned to the taxonomy."""

    def __init__(
        self,
        taxonomy: TaxonomyDocument,
        profile: Optional[ArchitectureProfile] = None,
    ) -> None:
        self.taxonomy = taxonomy
        self.profile = profile or ArchitectureProfile.from_metadata(taxonomy.metadata)
        self.ddl_generator = DDLGenerator(taxonomy, profile=self.profile)

    # ------------------------------------------------------------------
    # Top-level: build the full plan for a CREATE TABLE asset
    # ------------------------------------------------------------------
    def create_table_plan(
        self,
        options: DDLGenerationOptions,
        project: Optional[str] = None,
        warehouse: Optional[str] = None,
        location: Optional[str] = None,
    ) -> CLIPlan:
        """Build the full CLI plan to materialize a table on the active cloud."""
        ddl = self.ddl_generator.generate(options)
        cloud = self.profile.cloud.cloud
        title = self._asset_title(options)
        plan = CLIPlan(title=title, ddl=ddl)

        if cloud == "bigquery":
            plan.commands.extend(self._bigquery_table_commands(
                ddl=ddl, options=options, project=project, location=location,
            ))
        elif cloud == "snowflake":
            plan.commands.extend(self._snowflake_table_commands(
                ddl=ddl, options=options, warehouse=warehouse,
            ))
        elif cloud == "redshift":
            plan.commands.extend(self._redshift_table_commands(
                ddl=ddl, options=options,
            ))
        elif cloud == "databricks":
            plan.commands.extend(self._databricks_table_commands(
                ddl=ddl, options=options,
            ))
        else:
            plan.notes.append(
                f"No CLI generator for cloud '{cloud}'. DDL provided as-is — "
                "execute via your SQL client of choice."
            )

        if not self.profile.declared:
            plan.notes.append(
                "Architecture profile was inferred (not declared). Confirm the "
                "selected prefix and zone before running."
            )
        return plan

    # ------------------------------------------------------------------
    # Lake zone bucket / dataset provisioning
    # ------------------------------------------------------------------
    def create_zone_plan(
        self,
        zone_name: str,
        project: Optional[str] = None,
        region: str = "us-central1",
        bucket_prefix: str = "company",
    ) -> CLIPlan:
        """Provision the cloud storage / dataset for a declared lake zone."""
        zones = {(z.name or "").lower(): z for z in (self.taxonomy.lake_standards.zones or [])}
        zone = zones.get(zone_name.lower())
        if not zone:
            raise ValueError(
                f"Zone '{zone_name}' not declared in lake_standards.zones; "
                f"declared zones: {list(zones)}"
            )

        cloud = self.profile.cloud.cloud
        plan = CLIPlan(title=f"Provision zone '{zone_name}' on {cloud}")
        plan.notes.append(f"Retention policy: {zone.retention or 'not declared'}")

        if cloud == "bigquery":
            dataset = f"{zone_name}_layer"
            args = ["bq", "--location", region]
            if project:
                args.extend(["--project_id", project])
            args.extend(["mk", "--dataset", "--description", f"Lake zone '{zone_name}'"])
            args.append(f"{project}:{dataset}" if project else dataset)
            plan.commands.append(CLICommand(
                tool="bq", cloud="bigquery",
                description=f"Create BigQuery dataset for the '{zone_name}' zone",
                command=" ".join(shlex.quote(a) for a in args),
            ))
        elif cloud == "snowflake":
            plan.commands.append(CLICommand(
                tool="snowsql", cloud="snowflake",
                description=f"Create Snowflake schema for the '{zone_name}' zone",
                command="snowsql -q " + shlex.quote(
                    f"CREATE SCHEMA IF NOT EXISTS {zone_name.upper()}_LAYER "
                    f"COMMENT = 'Lake zone {zone_name}';"
                ),
            ))
        else:
            # Generic: GCS / S3 bucket aligned to zone alias
            alias = (zone.alias or zone_name).lower()
            bucket = f"{bucket_prefix}-{alias}-{region}"
            if cloud == "databricks":
                plan.commands.append(CLICommand(
                    tool="databricks", cloud="databricks",
                    description=f"Create Unity Catalog schema for '{zone_name}'",
                    command="databricks schemas create "
                    f"--catalog-name main --name {shlex.quote(zone_name)}_layer "
                    f"--comment {shlex.quote(f'Lake zone {zone_name}')}",
                ))
            else:
                plan.commands.append(CLICommand(
                    tool="gsutil", cloud="gcs",
                    description=f"Create GCS bucket aligned with the '{zone_name}' zone",
                    command=f"gsutil mb -l {shlex.quote(region)} "
                    + (f"-p {shlex.quote(project)} " if project else "")
                    + f"gs://{shlex.quote(bucket)}",
                    requires_auth=True,
                ))
                plan.commands.append(CLICommand(
                    tool="aws", cloud="s3",
                    description=f"(alternative) Create S3 bucket aligned with the '{zone_name}' zone",
                    command=f"aws s3 mb s3://{shlex.quote(bucket)} --region {shlex.quote(region)}",
                ))
        return plan

    # ------------------------------------------------------------------
    # Per-cloud table commands
    # ------------------------------------------------------------------
    def _bigquery_table_commands(self, *, ddl, options, project, location) -> List[CLICommand]:
        # `bq query` runs arbitrary SQL — preferred when DDL has comments/options.
        bq_args = ["bq"]
        if location:
            bq_args.extend(["--location", location])
        if project:
            bq_args.extend(["--project_id", project])
        bq_args.extend(["query", "--use_legacy_sql=false", "--nouse_cache", ddl])
        return [CLICommand(
            tool="bq", cloud="bigquery",
            description=f"Create table {self._fqn(options)} on BigQuery",
            command=" ".join(shlex.quote(a) for a in bq_args),
        )]

    def _snowflake_table_commands(self, *, ddl, options, warehouse) -> List[CLICommand]:
        # Use a session command file to keep the DDL readable and avoid escaping.
        preamble: List[str] = []
        if warehouse:
            preamble.append(f"USE WAREHOUSE {warehouse.upper()};")
        if options.database:
            preamble.append(f"USE DATABASE {options.database.upper()};")
        if options.schema:
            preamble.append(f"USE SCHEMA {options.schema.upper()};")
        full = "\n".join(preamble + [ddl])
        return [CLICommand(
            tool="snowsql", cloud="snowflake",
            description=f"Create table {self._fqn(options)} on Snowflake",
            command="snowsql -q " + shlex.quote(full),
        )]

    def _redshift_table_commands(self, *, ddl, options) -> List[CLICommand]:
        return [CLICommand(
            tool="psql", cloud="redshift",
            description=f"Create table {self._fqn(options)} on Redshift",
            command='psql "$REDSHIFT_URL" -c ' + shlex.quote(ddl),
        )]

    def _databricks_table_commands(self, *, ddl, options) -> List[CLICommand]:
        return [CLICommand(
            tool="databricks", cloud="databricks",
            description=f"Create table {self._fqn(options)} on Databricks",
            command="databricks sql query --query " + shlex.quote(ddl),
        )]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _asset_title(self, options: DDLGenerationOptions) -> str:
        prefix = options.architectural_prefix or ""
        if prefix and not prefix.endswith("_"):
            prefix = f"{prefix}_"
        return _cased(
            f"{prefix}{options.table_name}",
            self.profile.cloud.default_casing,
        )

    def _fqn(self, options: DDLGenerationOptions) -> str:
        parts = [p for p in (options.database, options.schema, self._asset_title(options)) if p]
        return ".".join(parts)
